### ISSUE TITLE
Improving the README.md 

### ISSUE THREAD

**Issue by luzpaz** [easyw/Defeaturing_WB#1]
Can we soup up the README.md file? Since this is what is displayed for the user when they are browsing the Addon Manager in FC ? Lets give it the same treatment that Manipulator got  ?

**Comment by easyw** [comment]
@luzpaz 
there is a wiki that could be (partially) converted to readme
https://www.freecadweb.org/wiki/Defeaturing_Workbench

**Comment by luzpaz** [comment]
We should do this soon. I imagine many people are missing the awesome features of this workbench due to it's very sparse and vague presentation on the Addon Manager

**Comment by easyw** [comment]
@luzpaz 
unfortunately I don't have spare time to do it ATM. If you want to port the wiki to the readme, I will pleased to merge your PR.

**Comment by luzpaz** [comment]
Need to remember to do this. This addon is under utilized since the readme is useless.

**Comment by luzpaz** [comment]
Placeholder for images 
![image](https://user-images.githubusercontent.com/4140247/112375777-117ad380-8cba-11eb-933d-88fa29aa2010.png)
