### ISSUE TITLE
  UnboundLocalError: local variable '_' referenced before assignment

### ISSUE THREAD

**Issue by MariwanJ** [easyw/Defeaturing_WB#8]
`if _.ShapeType != 'Shell': raise RuntimeError('Part object is not a shell')
`
\AppData\Roaming\FreeCAD\Mod\Defeaturing\DefeaturingTools.py", line 915, in removeFaces_RH
14:49:42      if _.ShapeType != 'Shell': raise RuntimeError('Part object is not a shell')
14:49:42  UnboundLocalError: local variable `'_' `referenced before assignment

**Comment by easyw** [comment]
@MariwanJ 
I would need more info to debug your issue... in which way can I trigger this error?

**Comment by MariwanJ** [comment]
I tried to remove a face from an object. So, if you want I must  test it again agains a file that I can upload it to you. But try to remove a face from an object.
But, the issue is clear. That _ is not defined and you are using it. Think about when that can happen.

**Comment by MariwanJ** [comment]
@easyw 
Just FYI
I decided to add your code to my WB. 
I will not fork it since FreeCADs manager cannot download forked WB code.
And I will be working on the tools to make it more general, more tools, better coverage..etc
