### ISSUE TITLE
Update to new FreeCAD AddonManager metadata schema

### ISSUE THREAD

**Issue by luzpaz** [easyw/Defeaturing_WB#9]
Please see https://github.com/FreeCAD/FreeCAD-addons/issues/200

**Comment by luzpaz** [comment]
bump

**Comment by luzpaz** [comment]
@easyw are you active these day?

**Comment by luzpaz** [comment]
:disappointed:

**Comment by luzpaz** [comment]
@easyw ping

**Comment by luzpaz** [comment]
@easyw ping

**Comment by easyw** [comment]
@luzpaz 
both Manipulator and Defeaturing WB should now be aligned to the new metadata package.xml

**Comment by luzpaz** [comment]
https://github.com/easyw/Defeaturing_WB/commit/82184f131440196e486a78d313d6a596e91af1b4
